# Generated by Django 2.1.5 on 2020-06-05 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_userorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNum', models.IntegerField()),
                ('price', models.FloatField()),
                ('status', models.BooleanField()),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.MenuItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('ItemTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ItemType')),
                ('topping1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping1', to='orders.Topping')),
                ('topping2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping2', to='orders.Topping')),
                ('topping3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping3', to='orders.Topping')),
            ],
        ),
        migrations.DeleteModel(
            name='DinnerPlatter',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='toppings',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.RemoveField(
            model_name='sicilianpizza',
            name='toppings',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='users',
        ),
        migrations.DeleteModel(
            name='RegularPizza',
        ),
        migrations.DeleteModel(
            name='SicilianPizza',
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
        migrations.AddField(
            model_name='itemtype',
            name='itemId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.MenuItem'),
        ),
    ]
