# Generated by Django 2.1.5 on 2020-06-05 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200604_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='completed',
        ),
    ]
