# Generated by Django 2.1.5 on 2020-06-05 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200604_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='topping1',
        ),
        migrations.RemoveField(
            model_name='price',
            name='topping2',
        ),
        migrations.RemoveField(
            model_name='price',
            name='topping3',
        ),
        migrations.AddField(
            model_name='order',
            name='topping1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping1', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='order',
            name='topping2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping2', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='order',
            name='topping3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping3', to='orders.Topping'),
        ),
    ]
