# Generated by Django 2.1.5 on 2020-06-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200604_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsExtraName', models.CharField(max_length=100)),
            ],
        ),
    ]
