# Generated by Django 2.1.5 on 2020-06-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_subsextra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubsExtra',
        ),
        migrations.AddField(
            model_name='topping',
            name='forPizza',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topping',
            name='forSub',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
