# Generated by Django 2.1.5 on 2020-06-06 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_auto_20200604_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.MenuItem')),
                ('itemType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.ItemType')),
                ('topping1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_topping1', to='orders.Topping')),
                ('topping2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_topping2', to='orders.Topping')),
                ('topping3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_topping3', to='orders.Topping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='topping1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_topping1', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='order',
            name='topping2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_topping2', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='order',
            name='topping3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_topping3', to='orders.Topping'),
        ),
    ]
