# Generated by Django 2.1.5 on 2020-06-06 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200606_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='UserOrder',
        ),
        migrations.RenameField(
            model_name='userorder',
            old_name='order',
            new_name='userOrder',
        ),
    ]
