# Generated by Django 2.1.5 on 2020-06-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200606_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='userOrder',
        ),
        migrations.AddField(
            model_name='cart',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
