# Generated by Django 2.1.5 on 2020-06-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200606_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='toppingsType',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
